import type { Metadata } from "next";
import { Roboto } from 'next/font/google'
import "./globals.css";

export const metadata: Metadata = {
  title: "Taweerat Portfolio",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ['latin'],
  weight: '300'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex-1 antialiased font-[Roboto]`}>
        {children}
      </body>
    </html>
  );
}
